apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aws-vpc-cni.fullname" . }}
  labels:
{{ include "aws-vpc-cni.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "aws-vpc-cni.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "aws-vpc-cni.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
{{- if .Values.nodeAgent.enablePolicyEventLogs -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks:aws-node-service-reader
subjects:
- kind: ServiceAccount
  name: aws-node
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: eks:service-reader
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
---
{{- if .Values.nodeAgent.enablePolicyEventLogs -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks:metadata-cache-binding
subjects:
- kind: ServiceAccount
  name: aws-k8s-metadata-serviceaccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: eks:pod-reader
  apiGroup: rbac.authorization.k8s.io
{{- end -}}