{{- if .Values.nodeAgent.enablePolicyEventLogs -}}
apiVersion: v1
kind: Service
metadata:
  name: aws-k8s-metadata-service
  namespace: default
  labels:
    app: metadata-cache
spec:
  selector:
    app: metadata-cache
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
{{- end -}}